name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-preview.1
    - name: Configure solution file
      run: echo "::set-env solution_path=action_state::'.\src\System.Activities.sln'"
    - name: Install dependencies
      run: dotnet restore ${solution_path}
    - name: Build
      run: dotnet build  ${solution_path} --configuration Release --no-restore
    - name: Test
      run: dotnet test ${solution_path} --no-restore --verbosity normal
