name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-preview.1
    - name: Configure solution file
      run: echo ::set-env SOLUTION_PATH='.\src\System.Activities.sln'
    - name: Install dependencies
      run: dotnet restore $SOLUTION_PATH
    - name: Build
      run: dotnet build  $SOLUTION_PATH --configuration Release --no-restore
    - name: Test
      run: dotnet test $SOLUTION_PATH --no-restore --verbosity normal
